package sx1276

const (
	RegLoRaFIFO                = 0x00
	RegLoRaOPMODE              = 0x01
	RegLoRaFRFMSB              = 0x06
	RegLoRaFRFMID              = 0x07
	RegLoRaFRFLSB              = 0x08
	RegLoRaPACONFIG            = 0x09
	RegLoRaPARAMP              = 0x0A
	RegLoRaOCP                 = 0x0B
	RegLoRaLNA                 = 0x0C
	RegLoRaFIFOADDRPTR         = 0x0D
	RegLoRaFIFOTXBASEADDR      = 0x0E
	RegLoRaFIFORXBASEADDR      = 0x0F
	RegLoRaFIFORXCURRENTADDR   = 0x10
	RegLoRaIRQFLAGSMASK        = 0x11
	RegLoRaIRQFLAGS            = 0x12
	RegLoRaRXNBBYTES           = 0x13
	RegLoRaRXHEADERCNTVALUEMSB = 0x14
	RegLoRaRXHEADERCNTVALUELSB = 0x15
	RegLoRaRXPACKETCNTVALUEMSB = 0x16
	RegLoRaRXPACKETCNTVALUELSB = 0x17
	RegLoRaMODEMSTAT           = 0x18
	RegLoRaPKTSNRVALUE         = 0x19
	RegLoRaPKTRSSIVALUE        = 0x1A
	RegLoRaRSSIVALUE           = 0x1B
	RegLoRaHOPCHANNEL          = 0x1C
	RegLoRaMODEMCONFIG1        = 0x1D
	RegLoRaMODEMCONFIG2        = 0x1E
	RegLoRaSYMBTIMEOUTLSB      = 0x1F
	RegLoRaPREAMBLEMSB         = 0x20
	RegLoRaPREAMBLELSB         = 0x21
	RegLoRaPAYLOADLENGTH       = 0x22
	RegLoRaPAYLOADMAXLENGTH    = 0x23
	RegLoRaHOPPERIOD           = 0x24
	RegLoRaFIFORXBYTEADDR      = 0x25
	RegLoRaMODEMCONFIG3        = 0x26
	RegLoRaFEIMSB              = 0x28
	RegLoRaFEIMID              = 0x29
	RegLoRaFEILSB              = 0x2A
	RegLoRaRSSIWIDEBAND        = 0x2C
	RegLoRaDETECTOPTIMIZE      = 0x31
	RegLoRaINVERTIQ            = 0x33
	RegLoRaDETECTIONTHRESHOLD  = 0x37
	RegLoRaSYNCWORD            = 0x39
	RegLoRaINVERTIQ2           = 0x3B
	RegLoRaDIOMAPPING1         = 0x40
	RegLoRaDIOMAPPING2         = 0x41
	RegLoRaVERSION             = 0x42
	RegLoRaPLLHOP              = 0x44
	RegLoRaTCXO                = 0x4B
	RegLoRaPADAC               = 0x4D
	RegLoRaFORMERTEMP          = 0x5B
	RegLoRaBITRATEFRAC         = 0x5D
	RegLoRaAGCREF              = 0x61
	RegLoRaAGCTHRESH1          = 0x62
	RegLoRaAGCTHRESH2          = 0x63
	RegLoRaAGCTHRESH3          = 0x64
	RegLoRaPLL                 = 0x70

	RegLoRaTEST2F = 0x2F
	RegLoRaTEST30 = 0x30
	RegLoRaTEST36 = 0x36
	RegLoRaTEST3A = 0x3A
)

const (
	LORA_OPMODE_LONGRANGEMODE_MASK byte = 0x7F
	LORA_OPMODE_LONGRANGEMODE_OFF  byte = 0x00 // Default
	LORA_OPMODE_LONGRANGEMODE_ON   byte = 0x80

	LORA_OPMODE_ACCESSSHAREDREG_MASK    byte = 0xBF
	LORA_OPMODE_ACCESSSHAREDREG_ENABLE  byte = 0x40
	LORA_OPMODE_ACCESSSHAREDREG_DISABLE byte = 0x00 // Default

	LORA_OPMODE_FREQMODE_ACCESS_MASK byte = 0xF7
	LORA_OPMODE_FREQMODE_ACCESS_LF   byte = 0x08 // Default
	LORA_OPMODE_FREQMODE_ACCESS_HF   byte = 0x00

	LORA_OPMODE_MASK            byte = 0xF8
	LORA_OPMODE_SLEEP           byte = 0x00
	LORA_OPMODE_STANDBY         byte = 0x01 // Default
	LORA_OPMODE_SYNTHESIZER_TX  byte = 0x02
	LORA_OPMODE_TRANSMITTER     byte = 0x03
	LORA_OPMODE_SYNTHESIZER_RX  byte = 0x04
	LORA_OPMODE_RECEIVER        byte = 0x05
	LORA_OPMODE_RECEIVER_SINGLE byte = 0x06
	LORA_OPMODE_CAD             byte = 0x07
)

const (
	LORA_PACONFIG_PASELECT_MASK    byte = 0x7F
	LORA_PACONFIG_PASELECT_PABOOST byte = 0x80
	LORA_PACONFIG_PASELECT_RFO     byte = 0x00 // Default

	LORA_PACONFIG_MAX_POWER_MASK byte = 0x8F

	LORA_PACONFIG_OUTPUTPOWER_MASK byte = 0xF0
)

const (
	LORA_PARAMP_TXBANDFORCE_MASK     byte = 0xEF
	LORA_PARAMP_TXBANDFORCE_BAND_SEL byte = 0x10
	LORA_PARAMP_TXBANDFORCE_AUTO     byte = 0x00 // Default

	LORA_PARAMP_MASK    byte = 0xF0
	LORA_PARAMP_3400_US byte = 0x00
	LORA_PARAMP_2000_US byte = 0x01
	LORA_PARAMP_1000_US byte = 0x02
	LORA_PARAMP_0500_US byte = 0x03
	LORA_PARAMP_0250_US byte = 0x04
	LORA_PARAMP_0125_US byte = 0x05
	LORA_PARAMP_0100_US byte = 0x06
	LORA_PARAMP_0062_US byte = 0x07
	LORA_PARAMP_0050_US byte = 0x08
	LORA_PARAMP_0040_US byte = 0x09 // Default
	LORA_PARAMP_0031_US byte = 0x0A
	LORA_PARAMP_0025_US byte = 0x0B
	LORA_PARAMP_0020_US byte = 0x0C
	LORA_PARAMP_0015_US byte = 0x0D
	LORA_PARAMP_0012_US byte = 0x0E
	LORA_PARAMP_0010_US byte = 0x0F
)

const (
	LORA_OCP_MASK byte = 0xDF
	LORA_OCP_ON   byte = 0x20 // Default
	LORA_OCP_OFF  byte = 0x00

	LORA_OCP_TRIM_MASK   byte = 0xE0
	LORA_OCP_TRIM_045_MA byte = 0x00
	LORA_OCP_TRIM_050_MA byte = 0x01
	LORA_OCP_TRIM_055_MA byte = 0x02
	LORA_OCP_TRIM_060_MA byte = 0x03
	LORA_OCP_TRIM_065_MA byte = 0x04
	LORA_OCP_TRIM_070_MA byte = 0x05
	LORA_OCP_TRIM_075_MA byte = 0x06
	LORA_OCP_TRIM_080_MA byte = 0x07
	LORA_OCP_TRIM_085_MA byte = 0x08
	LORA_OCP_TRIM_090_MA byte = 0x09
	LORA_OCP_TRIM_095_MA byte = 0x0A
	LORA_OCP_TRIM_100_MA byte = 0x0B // Default
	LORA_OCP_TRIM_105_MA byte = 0x0C
	LORA_OCP_TRIM_110_MA byte = 0x0D
	LORA_OCP_TRIM_115_MA byte = 0x0E
	LORA_OCP_TRIM_120_MA byte = 0x0F
	LORA_OCP_TRIM_130_MA byte = 0x10
	LORA_OCP_TRIM_140_MA byte = 0x11
	LORA_OCP_TRIM_150_MA byte = 0x12
	LORA_OCP_TRIM_160_MA byte = 0x13
	LORA_OCP_TRIM_170_MA byte = 0x14
	LORA_OCP_TRIM_180_MA byte = 0x15
	LORA_OCP_TRIM_190_MA byte = 0x16
	LORA_OCP_TRIM_200_MA byte = 0x17
	LORA_OCP_TRIM_210_MA byte = 0x18
	LORA_OCP_TRIM_220_MA byte = 0x19
	LORA_OCP_TRIM_230_MA byte = 0x1A
	LORA_OCP_TRIM_240_MA byte = 0x1B
)

const (
	LORA_LNA_GAIN_MASK byte = 0x1F
	LORA_LNA_GAIN_G1   byte = 0x20 // Default
	LORA_LNA_GAIN_G2   byte = 0x40
	LORA_LNA_GAIN_G3   byte = 0x60
	LORA_LNA_GAIN_G4   byte = 0x80
	LORA_LNA_GAIN_G5   byte = 0xA0
	LORA_LNA_GAIN_G6   byte = 0xC0

	LORA_LNA_BOOST_LF_MASK    byte = 0xE7
	LORA_LNA_BOOST_LF_DEFAULT byte = 0x00 // Default

	LORA_LNA_BOOST_HF_MASK byte = 0xFC
	LORA_LNA_BOOST_HF_OFF  byte = 0x00 // Default
	LORA_LNA_BOOST_HF_ON   byte = 0x03
)

const (
	LORA_FIFOADDRPTR byte = 0x00 // Default

	LORA_FIFOTXBASEADDR byte = 0x80 // Default

	LORA_FIFORXBASEADDR byte = 0x00 // Default
)

const (
	LORA_IRQFLAGS_RXTIMEOUT_MASK          byte = 0x80
	LORA_IRQFLAGS_RXDONE_MASK             byte = 0x40
	LORA_IRQFLAGS_PAYLOADCRCERROR_MASK    byte = 0x20
	LORA_IRQFLAGS_VALIDHEADER_MASK        byte = 0x10
	LORA_IRQFLAGS_TXDONE_MASK             byte = 0x08
	LORA_IRQFLAGS_CADDONE_MASK            byte = 0x04
	LORA_IRQFLAGS_FHSSCHANGEDCHANNEL_MASK byte = 0x02
	LORA_IRQFLAGS_CADDETECTED_MASK        byte = 0x01
)

const (
	LORA_IRQFLAGS_RXTIMEOUT          byte = 0x80
	LORA_IRQFLAGS_RXDONE             byte = 0x40
	LORA_IRQFLAGS_PAYLOADCRCERROR    byte = 0x20
	LORA_IRQFLAGS_VALIDHEADER        byte = 0x10
	LORA_IRQFLAGS_TXDONE             byte = 0x08
	LORA_IRQFLAGS_CADDONE            byte = 0x04
	LORA_IRQFLAGS_FHSSCHANGEDCHANNEL byte = 0x02
	LORA_IRQFLAGS_CADDETECTED        byte = 0x01
)

const (
	LORA_MODEMSTAT_RX_CR_MASK        byte = 0x1F
	LORA_MODEMSTAT_MODEM_STATUS_MASK byte = 0xE0
)

const (
	LORA_HOPCHANNEL_PLL_LOCK_TIMEOUT_MASK byte = 0x7F
	LORA_HOPCHANNEL_PLL_LOCK_FAIL         byte = 0x80
	LORA_HOPCHANNEL_PLL_LOCK_SUCCEED      byte = 0x00 // Default

	LORA_HOPCHANNEL_CRCONPAYLOAD_MASK byte = 0xBF
	LORA_HOPCHANNEL_CRCONPAYLOAD_ON   byte = 0x40
	LORA_HOPCHANNEL_CRCONPAYLOAD_OFF  byte = 0x00 // Default

	LORA_HOPCHANNEL_CHANNEL_MASK byte = 0x3F
)

const (
	LORA_MODEMCONFIG1_BW_MASK      byte = 0x0F
	LORA_MODEMCONFIG1_BW_7_81_KHZ  byte = 0x00
	LORA_MODEMCONFIG1_BW_10_41_KHZ byte = 0x10
	LORA_MODEMCONFIG1_BW_15_62_KHZ byte = 0x20
	LORA_MODEMCONFIG1_BW_20_83_KHZ byte = 0x30
	LORA_MODEMCONFIG1_BW_31_25_KHZ byte = 0x40
	LORA_MODEMCONFIG1_BW_41_66_KHZ byte = 0x50
	LORA_MODEMCONFIG1_BW_62_50_KHZ byte = 0x60
	LORA_MODEMCONFIG1_BW_125_KHZ   byte = 0x70 // Default
	LORA_MODEMCONFIG1_BW_250_KHZ   byte = 0x80
	LORA_MODEMCONFIG1_BW_500_KHZ   byte = 0x90

	LORA_MODEMCONFIG1_CODINGRATE_MASK byte = 0xF1
	LORA_MODEMCONFIG1_CODINGRATE_4_5  byte = 0x02
	LORA_MODEMCONFIG1_CODINGRATE_4_6  byte = 0x04 // Default
	LORA_MODEMCONFIG1_CODINGRATE_4_7  byte = 0x06
	LORA_MODEMCONFIG1_CODINGRATE_4_8  byte = 0x08

	LORA_MODEMCONFIG1_IMPLICITHEADER_MASK byte = 0xFE
	LORA_MODEMCONFIG1_IMPLICITHEADER_ON   byte = 0x01
	LORA_MODEMCONFIG1_IMPLICITHEADER_OFF  byte = 0x00 // Default
)

const (
	LORA_MODEMCONFIG2_SF_MASK byte = 0x0F
	LORA_MODEMCONFIG2_SF_6    byte = 0x60
	LORA_MODEMCONFIG2_SF_7    byte = 0x70 // Default
	LORA_MODEMCONFIG2_SF_8    byte = 0x80
	LORA_MODEMCONFIG2_SF_9    byte = 0x90
	LORA_MODEMCONFIG2_SF_10   byte = 0xA0
	LORA_MODEMCONFIG2_SF_11   byte = 0xB0
	LORA_MODEMCONFIG2_SF_12   byte = 0xC0

	LORA_MODEMCONFIG2_TXCONTINUOUSMODE_MASK byte = 0xF7
	LORA_MODEMCONFIG2_TXCONTINUOUSMODE_ON   byte = 0x08
	LORA_MODEMCONFIG2_TXCONTINUOUSMODE_OFF  byte = 0x00

	LORA_MODEMCONFIG2_RXPAYLOADCRC_MASK byte = 0xFB
	LORA_MODEMCONFIG2_RXPAYLOADCRC_ON   byte = 0x04
	LORA_MODEMCONFIG2_RXPAYLOADCRC_OFF  byte = 0x00 // Default

	LORA_MODEMCONFIG2_SYMBTIMEOUTMSB_MASK byte = 0xFC
	LORA_MODEMCONFIG2_SYMBTIMEOUTMSB      byte = 0x00 // Default
)

const (
	LORA_SYMBTIMEOUTLSB_SYMBTIMEOUT  byte = 0x64 // Default
	LORA_PREAMBLELENGTHMSB           byte = 0x00 // Default
	LORA_PREAMBLELENGTHLSB           byte = 0x08 // Default
	LORA_PAYLOADLENGTH               byte = 0x0E // Default
	LORA_PAYLOADMAXLENGTH            byte = 0xFF // Default
	LORA_HOPPERIOD_FREQFOPPINGPERIOD byte = 0x00 // Default
)

const (
	LORA_MODEMCONFIG3_LOWDATARATEOPTIMIZE_MASK byte = 0xF7
	LORA_MODEMCONFIG3_LOWDATARATEOPTIMIZE_ON   byte = 0x08
	LORA_MODEMCONFIG3_LOWDATARATEOPTIMIZE_OFF  byte = 0x00 // Default

	LORA_MODEMCONFIG3_AGCAUTO_MASK byte = 0xFB
	LORA_MODEMCONFIG3_AGCAUTO_ON   byte = 0x04 // Default
	LORA_MODEMCONFIG3_AGCAUTO_OFF  byte = 0x00
)

const (
	LORA_DETECTIONOPTIMIZE_MASK        byte = 0xF8
	LORA_DETECTIONOPTIMIZE_SF7_TO_SF12 byte = 0x03 // Default
	LORA_DETECTIONOPTIMIZE_SF6         byte = 0x05
)

const (
	LORA_INVERTIQ_RX_MASK byte = 0xBF
	LORA_INVERTIQ_RX_OFF  byte = 0x00
	LORA_INVERTIQ_RX_ON   byte = 0x40
	LORA_INVERTIQ_TX_MASK byte = 0xFE
	LORA_INVERTIQ_TX_OFF  byte = 0x01
	LORA_INVERTIQ_TX_ON   byte = 0x00
)

const (
	LORA_DETECTIONTHRESH_SF7_TO_SF12 byte = 0x0A // Default
	LORA_DETECTIONTHRESH_SF6         byte = 0x0C
)

const (
	LORA_INVERTIQ2_ON  byte = 0x19
	LORA_INVERTIQ2_OFF byte = 0x1D
)

const (
	LORA_DIOMAPPING1_DIO0_MASK byte = 0x3F
	LORA_DIOMAPPING1_DIO0_00   byte = 0x00 // Default
	LORA_DIOMAPPING1_DIO0_01   byte = 0x40
	LORA_DIOMAPPING1_DIO0_10   byte = 0x80
	LORA_DIOMAPPING1_DIO0_11   byte = 0xC0

	LORA_DIOMAPPING1_DIO1_MASK byte = 0xCF
	LORA_DIOMAPPING1_DIO1_00   byte = 0x00 // Default
	LORA_DIOMAPPING1_DIO1_01   byte = 0x10
	LORA_DIOMAPPING1_DIO1_10   byte = 0x20
	LORA_DIOMAPPING1_DIO1_11   byte = 0x30

	LORA_DIOMAPPING1_DIO2_MASK byte = 0xF3
	LORA_DIOMAPPING1_DIO2_00   byte = 0x00 // Default
	LORA_DIOMAPPING1_DIO2_01   byte = 0x04
	LORA_DIOMAPPING1_DIO2_10   byte = 0x08
	LORA_DIOMAPPING1_DIO2_11   byte = 0x0C

	LORA_DIOMAPPING1_DIO3_MASK byte = 0xFC
	LORA_DIOMAPPING1_DIO3_00   byte = 0x00 // Default
	LORA_DIOMAPPING1_DIO3_01   byte = 0x01
	LORA_DIOMAPPING1_DIO3_10   byte = 0x02
	LORA_DIOMAPPING1_DIO3_11   byte = 0x03
)

const (
	LORA_DIOMAPPING2_DIO4_MASK byte = 0x3F
	LORA_DIOMAPPING2_DIO4_00   byte = 0x00 // Default
	LORA_DIOMAPPING2_DIO4_01   byte = 0x40
	LORA_DIOMAPPING2_DIO4_10   byte = 0x80
	LORA_DIOMAPPING2_DIO4_11   byte = 0xC0

	LORA_DIOMAPPING2_DIO5_MASK byte = 0xCF
	LORA_DIOMAPPING2_DIO5_00   byte = 0x00 // Default
	LORA_DIOMAPPING2_DIO5_01   byte = 0x10
	LORA_DIOMAPPING2_DIO5_10   byte = 0x20
	LORA_DIOMAPPING2_DIO5_11   byte = 0x30

	LORA_DIOMAPPING2_MAP_MASK           byte = 0xFE
	LORA_DIOMAPPING2_MAP_PREAMBLEDETECT byte = 0x01
	LORA_DIOMAPPING2_MAP_RSSI           byte = 0x00 // Default
)

const (
	LORA_PLLHOP_FASTHOP_MASK byte = 0x7F
	LORA_PLLHOP_FASTHOP_ON   byte = 0x80
	LORA_PLLHOP_FASTHOP_OFF  byte = 0x00 // Default
)

const (
	LORA_TCXO_TCXOINPUT_MASK byte = 0xEF
	LORA_TCXO_TCXOINPUT_ON   byte = 0x10
	LORA_TCXO_TCXOINPUT_OFF  byte = 0x00 // Default
)

const (
	LORA_PADAC_20DBM_MASK byte = 0xF8
	LORA_PADAC_20DBM_ON   byte = 0x07
	LORA_PADAC_20DBM_OFF  byte = 0x04 // Default
)
